### ISSUE TITLE
Error when running ESLint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#54]
Looks like we need to maybe need to add ["eslint-config-nightmare-mode"](http://npm.im/eslint-config-nightmare-mode) as a devDep?

```sh
$ eslint .

Cannot find module 'eslint-config-nightmare-mode'
Referenced from: /Users/pdehaan/dev/github/mozilla/testpilot-containers/.eslintrc.js
Error: Cannot find module 'eslint-config-nightmare-mode'
Referenced from: /Users/pdehaan/dev/github/mozilla/testpilot-containers/.eslintrc.js
    at ModuleResolver.resolve (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config/config-file.js:495:26)
    at configExtends.reduceRight (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/pdehaan/dev/github/mozilla/testpilot-containers/node_modules/eslint/lib/config.js:259:26)

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/pdehaan/.nvm/versions/node/v7.4.0/bin/node" "/Users/pdehaan/.nvm/versions/node/v7.4.0/bin/npm" "run" "lint"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! testpilot-containers@0.0.1 lint: `eslint .`
npm ERR! Exit status 1
```

**Comment by pdehaan** [comment]
After adding **nightmare-mode** and re-running ESLint, I'm getting 262 errors, 0 warnings locally.
Rerunning with `$ eslint . --fix`, I get it down to 87 errors, 0 warnings.

Looks like we may need to tweak some rules and/or configs (and possibly some code).

**Comment by jonathanKingston** [comment]
Remove nightmare-mode for the time being it is clearly too strict 👍 I wanted to do a Firefox style equiv but yeah there are better things to be doing right now.

Most of those errors I think will be on the dependencies and random things that should be excluded as are imported bits of code.

@groovecoder do we have a plan on what config we should use? Or should I get making one (we can add to nightmare-mode and you can have sub configs like the nightmare-mode/node I have etc?

**Comment by pdehaan** [comment]
Maybe as a first pass, we relax the ESLint config to "eslint:recommended" with a few bonus rules?

```js
module.exports = {
  env: {
    es6: true,
    node: true
  },
  extends: [
    'eslint:recommended'
    // 'nightmare-mode/node'
  ],
  rules: {
    'eqeqeq': 'error',
    'indent': ['error', 2],
    'no-var': 'error',
    'prefer-const': 'error',
    'quotes': ['error', 'double']
  }
};
```

That gives me 163 errors against master, but quickly drops to a manageable 27 if we do `eslint . --fix` to autofix some quotes and other formatting errors.

The remaining errors seem to be a mix of `no-unused-vars`, and `eqeqeq`.

**Comment by bakulf** [comment]
I submitted a pull-request yesterday.
